version: 2
updates: 
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: pub
    directory: /example
    schedule:
      interval: monthly
    groups:
      example-pub:
        patterns:
          - "*"
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: monthly
    groups:
      root-pub:
        patterns:
          - "*"
