include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: true
    one_member_abstracts: false


analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/src/version.dart"