name: cached_value
description: A simple way to cache values that result from rather expensive operations.
version: 0.1.0
repository: https://github.com/renancaraujo/cached_value

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0

dev_dependencies:
  test: ^1.17.2
  meta: ^1.3.0
  effective_dart: ^1.3.1
