name: cached_value
description: A simple way to cache values that result from rather expensive operations.
version: 1.0.0
repository: https://github.com/bluefireteam/cached_value
issue_tracker: https://github.com/bluefireteam/cached_value/issues
homepage: https://github.com/bluefireteam/cached_value
documentation: https://github.com/bluefireteam/cached_value?tab=readme-ov-file#cached_value
topics: [cache, memoization, caching]

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.25.8
  very_good_analysis: ^6.0.0
